# Generated by Django 5.1.1 on 2024-09-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'nombre_corto')},
        ),
    ]
